"""phase 5 optimization options and recommendations

Revision ID: 271c8b852322
Revises: 662f7bd1b2db
Create Date: 2026-09-24 20:45:48.009246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271c8b852322'
down_revision: Union[str, Sequence[str], None] = '662f7bd1b2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_version_id', sa.String(length=36), nullable=True),
    sa.Column('runs_analyzed', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_recommendations_agent_id'), 'optimization_recommendations', ['agent_id'], unique=False)
    op.add_column('agent_versions', sa.Column('options', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('llm_calls', sa.Column('purpose', sa.String(length=20), nullable=False, server_default='agent'))
    op.add_column('run_steps', sa.Column('turn', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('runs', sa.Column('tool_calls_skipped', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('runs', sa.Column('route', sa.String(length=50), nullable=True))
    op.add_column('runs', sa.Column('routed_model', sa.String(length=100), nullable=True))
    op.add_column('tool_calls', sa.Column('skip_reason', sa.String(length=20), nullable=True))
    # Backfill turns for existing traces: a step belongs to the turn of the latest LLM call
    # at or before it (LLM calls start turns 1, 2, ...). Routing did not exist yet.
    op.execute(
        """
        UPDATE run_steps SET turn = (
          SELECT COUNT(*) FROM run_steps l
          WHERE l.run_id = run_steps.run_id AND l.type = 'llm_call'
            AND l.sequence <= run_steps.sequence
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_calls', 'skip_reason')
    op.drop_column('runs', 'routed_model')
    op.drop_column('runs', 'route')
    op.drop_column('runs', 'tool_calls_skipped')
    op.drop_column('run_steps', 'turn')
    op.drop_column('llm_calls', 'purpose')
    op.drop_column('agent_versions', 'options')
    op.drop_index(op.f('ix_optimization_recommendations_agent_id'), table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    # ### end Alembic commands ###
