"""task leases

Revision ID: d0422f98b169
Revises: 271c42e0ef28
Create Date: 2026-09-24 21:31:16.847950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0422f98b169'
down_revision: Union[str, Sequence[str], None] = '271c42e0ef28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('lease_owner', sa.String(length=64), nullable=True))
    op.add_column('evaluations', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('experiments', sa.Column('lease_owner', sa.String(length=64), nullable=True))
    op.add_column('experiments', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'lease_expires_at')
    op.drop_column('experiments', 'lease_owner')
    op.drop_column('evaluations', 'lease_expires_at')
    op.drop_column('evaluations', 'lease_owner')
    # ### end Alembic commands ###
